"""change table

Revision ID: 117e205f9e15
Revises: e27894b48565
Create Date: 2018-10-23 16:26:52.503089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117e205f9e15'
down_revision = 'e27894b48565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assigned_to', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('severity', sa.String(length=100), nullable=True))
    op.add_column('tickets', sa.Column('status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'status')
    op.drop_column('tickets', 'severity')
    op.drop_column('tickets', 'assigned_to')
    # ### end Alembic commands ###
